### ISSUE TITLE
Potential overflow in ModuleKey::from_members

### ISSUE THREAD

**Issue by MavethGH** [robtfm/naga_oil#1]
https://github.com/robtfm/naga_oil/blob/66f25d5cdd68d9e1c62eb449a1356f9effddb025/src/compose/mod.rs#L152
This will overflow if there are more than 64 items in `universe`, which seems quite possible seeing as this gets passed the list of all shader defs that can affect a module.

**Comment by robtfm** [comment]
sorry for all the noise, i meant to give you some time to check the changes, but then committed to master by mistake. i reverted that now and made a new pr with the same changes in

**Comment by MavethGH** [comment]
Yeah, I can't think of a better way to do it than with a BitSet. It shouldn't impact performance much, and even if it did, this isn't code that's getting run many times every frame, so it doesn't really matter.

**Comment by MavethGH** [comment]
Oops didn't mean to close that :laughing:
