### ISSUE TITLE
Update to naga 0.12.0

### ISSUE THREAD

**Issue by Dinnerbone** [robtfm/naga_oil#17]
wgpu 0.16.0 came out and with it, naga 0.12. Can you update naga_oil to use it please?

I had a go at updating naga_oil to it myself but I hit a bump when it came to https://github.com/gfx-rs/naga/pull/2264 and I wasn't confident enough in knowing the code of this library to continue. Otherwise the changes weren't that difficult.

Thanks!

**Comment by robtfm** [comment]
i'll try and get to this soon. if you've got an otherwise-working fork you could try using a `Composer::non_validating()` - i'm not sure if that'll help but it's worth a shot.
